server:
  port: 5002
spring:
  application:
    name: delta-service
    # 设置实时刷新
    cache: false
    # 模板引擎访问前缀
    prefix: classpath:/templates/
# 要跳转的服务中心地址
sso-server-url-prefix: http://10.100.1.97:5000/sso
# 当前应用的地址
client-host-url: http://127.0.0.1:5002
# 客户端退出接口
client-logout-url: /logout
