server:
  port: 5004
spring:
  application:
    name: beta-service
    # 设置实时刷新
    cache: false
    # 模板引擎访问前缀
    prefix: classpath:/templates/
# 要跳转的服务中心地址
sso-server-url-prefix: http://192.168.1.9:5000/sso
# 当前应用的地址
client-host-url: http://127.0.0.1:5004
# 客户端退出接口
client-logout-url: /logout
